// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

type iconOpt struct {
	styles map[string]string
	color  string
}

type IconOptFunc func(*iconOpt)

func WithColor(color string) IconOptFunc {
	return func(o *iconOpt) {
		o.color = color
	}
}

func WithStyle(key, value string) IconOptFunc {
	return func(o *iconOpt) {
		o.styles[key] = value
	}
}

func parseOpts(size string, opts ...IconOptFunc) iconOpt {
	_opts := iconOpt{color: "#000", styles: map[string]string{}}
	for _, o := range opts {
		o(&_opts)
	}
	_opts.styles["width"] = size
	_opts.styles["height"] = size
	_opts.styles["display"] = "inline-block"
	return _opts
}

func DoubleIcon(size string, opts ...IconOptFunc) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_opts := parseOpts(size, opts...)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(_opts.styles)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 37, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><svg viewbox=\"0 0 245 245\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g transform=\"matrix(3.7795276,0,0,3.7795276,415.52916,-254.86537)\"><path style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(templ.SafeCSS(fmt.Sprintf("fill: %s", _opts.color)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 41, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" d=\"m -86.807679,101.7092 6.5951,9.68209 h -5.10547 l -4.44342,-6.48014 -4.40523,6.48014 h -5.13094 l 6.59511,-9.68209 -6.34047,-9.288198 h 5.11821 l 4.16332,6.11166 4.15058,-6.11166 h 5.14368 z\"></path> <path style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(templ.SafeCSS(fmt.Sprintf("fill: %s", _opts.color)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 45, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" d=\"m -58.086539,111.39129 h -19.31387 v -3.68607 l 6.92822,-6.35409 q 2.09008,-1.965908 3.36734,-3.264808 1.27728,-1.33401 1.85785,-2.38717 0.58058,-1.08827 0.58058,-2.31696 0,-1.50953 -0.92893,-2.24675 -0.89022,-0.73721 -2.43842,-0.73721 -1.58691,0 -3.0964,0.667 -1.50951,0.667 -3.17383,1.8957 l -3.17382,-3.40523 q 1.19986,-0.94785 2.51584,-1.75528 1.35468,-0.80742 3.09641,-1.2989 1.78043,-0.52658 4.25756,-0.52658 2.70935,0 4.64461,0.91274 1.97396,0.87764 3.019,2.42228 1.08375,1.50953 1.08375,3.44033 0,2.07123 -0.92893,3.79139 -0.89022,1.72017 -2.63196,3.40523 -1.703,1.685058 -4.14144,3.721178 l -3.56087,3.01907 v 0.24574 h 12.03731 z\"></path> <path style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("fill: none", "stroke-width: 2.5", templ.SafeCSS(fmt.Sprintf("stroke: %s", _opts.color)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 49, Col: 101}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" d=\"m -91.692093,68.683128 h 26 c 9.418,0 17,7.582 17,17 v 26.000002 c 0,9.418 -7.582,17 -17,17 h -26 c -9.417997,0 -16.999997,-7.582 -16.999997,-17 V 85.683128 c 0,-9.418 7.582,-17 16.999997,-17 z\"></path></g></svg></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ShoutIcon(size string, opts ...IconOptFunc) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_opts := parseOpts(size, opts...)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<span style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(_opts.styles)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 59, Col: 27}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"><svg viewBox=\"0 0 512 512\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><g stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\"><g id=\"drop\" fill=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(_opts.color)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/icons.templ`, Line: 62, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" transform=\"translate(42.666667, 128.000000)\"><path d=\"M85.333,55.466 L106.666667,53.3333333 L320,0 C334.222222,42.6666667 341.333333,85.3333333 341.333333,128 C341.333333,170.666667 334.222222,213.333333 320,256 L202.143432,226.536015 C198.2986,255.215667 173.732229,277.333333 144,277.333333 C112.799321,277.333333 87.2873754,252.976969 85.4404009,222.240476 L85.3333333,218.666667 L85.333,55.466 Z M359.264043,179.197776 L421.623727,193.594643 L412.025816,235.167766 L349.666132,220.770899 L359.264043,179.197776 Z M128,208 L128,218.666667 C128,227.503223 135.163444,234.666667 144,234.666667 C152.100176,234.666667 158.794474,228.647384 159.853939,220.837772 L160,218.666667 L160,216 L128,208 Z M64,57.6 L64,198.4 L3.55271368e-14,192 L3.55271368e-14,64 L64,57.6 Z M426.666667,106.666667 L426.666667,149.333333 L362.666667,149.333333 L362.666667,106.666667 L426.666667,106.666667 Z M412.025816,20.8322337 L421.623727,62.4053565 L359.264043,76.802224 L349.666132,35.2291012 L412.025816,20.8322337 Z\" id=\"Combined-Shape\"></path></g></g></svg></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
